FROM influxdb 
#this conf file configed to listen 4243 for opentsdb
#changes:
#added the folowing lines
#[[opentsdb]]
#   enabled = true
#   bind-address = ":4242"
#   database = "opentsdb"
#

COPY influxdb.conf /etc/influxdb/

